name: publish

on:
  push:
    branches:
      - develop
      - /^release\/v?(\d|\.)*/
    tags:
      - /v?(\d|\.)*/
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Configure Build
        run: |
          TARGET_ENV=prod
          if [ {{ github.ref_type == 'branch' }} && {{ github.ref != 'develop' }} ]; then
             IMAGE_TAG=`echo ${{ github.ref }} | cut -d/ -f4`
             TARGET_ENV=uat
          else
             IMAGE_TAG=`echo "${{ github.ref }}" | cut -d/ -f3`
             if [ {{ github.ref_type == 'branch' }} ]; then
                TARGET_ENV=dev
             fi
          fi

          echo $IMAGE_TAG
          echo $TARGET_ENV