name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # The Checkout actions at v2 and beyond prevent pushes as another user due to persist-credentials being set to true by default
          # persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx release-it --minor
        if: ${{ github.ref == 'ref/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx release-it --preRelease=next
        if: ${{ github.ref == 'ref/heads/next' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


