name: ci

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set author identity
        run: |
          git config --global user.email "me@jerrythomas.name"
          git config --global user.name "Jerry Thomas"
      - name: Bump pre-release version
        if: ${{ github.ref }} == 'refs/head/next'
        run: npm version prerelease --preid=next
      - name: Bump release version
        if: ${{ github.ref }} == 'refs/head/main'
        run: |
          echo "patch"
          echo ${{ github.ref }}
          npm run bump:patch
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm publish --ignore-scripts